services:
    app:
        build: .
        ports:
            - '${PORT:-3500}:${PORT:-3500}'
        env_file:
            - .env
        environment:
            - TZ=Asia/Seoul
        volumes:
            - ./:/app
            - ./logs:/app/logs
        restart: always
